# Generated by Django 6.0.2 on 2026-03-02 02:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('customer_type', models.CharField(choices=[('B2B', 'Professionnel (B2B)'), ('B2C', 'Particulier (B2C)')], default='B2C', max_length=3, verbose_name='Type')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(default='Abidjan', max_length=100, verbose_name='Ville')),
                ('company_registration', models.CharField(blank=True, max_length=50, verbose_name='N° RCCM')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='N° Contribuable')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum autorisé en crédit', max_digits=14, verbose_name='Plafond de crédit (FCFA)')),
                ('payment_terms', models.PositiveIntegerField(default=0, help_text='0 = paiement comptant', verbose_name='Délai de paiement (jours)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Positif = dette du client, Négatif = avoir', max_digits=14, verbose_name='Solde actuel (FCFA)')),
                ('is_blocked', models.BooleanField(default=False, help_text='Si coché, aucune nouvelle commande acceptée', verbose_name='Compte bloqué')),
                ('manual_score', models.PositiveIntegerField(default=5, help_text='Note attribuée par le gestionnaire', verbose_name='Note manuelle (1-10)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('stock', 'Stock'), ('alert', 'Alerte'), ('info', 'Information')], default='info', max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, help_text="URL vers l'objet concerné", max_length=500, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web_form', 'Formulaire web'), ('phone', 'Téléphone'), ('whatsapp', 'WhatsApp'), ('direct', 'Direct (magasin)')], default='web_form', max_length=20, verbose_name='Source')),
                ('prospect_name', models.CharField(blank=True, max_length=200, verbose_name='Nom prospect')),
                ('prospect_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone prospect')),
                ('prospect_email', models.EmailField(blank=True, max_length=254, verbose_name='Email prospect')),
                ('prospect_address', models.TextField(blank=True, verbose_name='Adresse prospect')),
                ('prospect_type', models.CharField(choices=[('B2B', 'Professionnel (B2B)'), ('B2C', 'Particulier (B2C)')], default='B2C', max_length=3, verbose_name='Type prospect')),
                ('items', models.JSONField(default=list, help_text='[{"product_id": 1, "quantity": 10, "unit_price": 5000}]', verbose_name='Articles commandés')),
                ('total_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total demandé (FCFA)')),
                ('payment_preference', models.CharField(blank=True, max_length=50, verbose_name='Préférence paiement')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Message')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('processing', 'En traitement'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('converted', 'Convertie en commande')], default='new', max_length=20, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to='crm.customer', verbose_name='Client existant')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de commande',
                'verbose_name_plural': 'Inbox commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('sac_50kg', 'Sac de 50 kg'), ('tonne', 'Tonne'), ('unite', 'Unité')], default='sac_50kg', max_length=20, verbose_name='Unité')),
                ('price_b2b', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix B2B')),
                ('price_b2c', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix B2C')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité en stock')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name="Seuil d'alerte")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='crm.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
    ]
