# Generated by Django 6.0.2 on 2026-03-02 02:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_invoice_invoiceitem_order_invoice_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Caisse principale', max_length=50, verbose_name='Nom caisse')),
                ('session_date', models.DateField(verbose_name='Date session')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde ouverture')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde clôture')),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde théorique')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total espèces')),
                ('total_mobile_money', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Mobile Money')),
                ('total_bank', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total virement/chèque')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Clôturée')], default='open', max_length=10, verbose_name='Statut')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ouvert le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-session_date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='crm.cashregister')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant initial')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant restant')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='crm.customer', verbose_name='Client')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='crm.invoice', verbose_name='Facture origine')),
            ],
            options={
                'verbose_name': 'Avoir client',
                'verbose_name_plural': 'Avoirs clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('payment_type', models.CharField(choices=[('payment', 'Encaissement'), ('refund', 'Remboursement'), ('credit_note', 'Avoir'), ('adjustment', 'Ajustement')], default='payment', max_length=20, verbose_name='Type')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('credit', 'Crédit client')], default='cash', max_length=20, verbose_name='Méthode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date paiement')),
                ('transaction_ref', models.CharField(blank=True, help_text='Numéro de transaction mobile money, chèque, etc.', max_length=100, verbose_name='Réf. transaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.cashregister', verbose_name='Caisse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.customer', verbose_name='Client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.invoice', verbose_name='Facture')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debit', 'Débit (dette)'), ('credit', 'Crédit (paiement)')], max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde après')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='crm.customer', verbose_name='Client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='crm.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='crm.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='crm.payment')),
            ],
            options={
                'verbose_name': 'Écriture client',
                'verbose_name_plural': 'Grand livre client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Date échéance')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Date rappel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='crm.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='crm.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.payment')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéancier',
                'ordering': ['due_date'],
            },
        ),
    ]
