# Generated by Django 6.0.2 on 2026-03-02 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_phase3_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_score', models.IntegerField(default=50, help_text='Régularité des paiements', verbose_name='Score paiement')),
                ('volume_score', models.IntegerField(default=50, help_text="Volume d'achat", verbose_name='Score volume')),
                ('frequency_score', models.IntegerField(default=50, help_text='Fréquence des commandes', verbose_name='Score fréquence')),
                ('loyalty_score', models.IntegerField(default=50, help_text='Ancienneté et régularité', verbose_name='Score fidélité')),
                ('auto_score', models.IntegerField(default=50, verbose_name='Score automatique')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Nb commandes')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='CA total')),
                ('avg_payment_delay', models.IntegerField(default=0, verbose_name='Délai paiement moyen (j)')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='Dernière commande')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Dernier calcul')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_detail', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Score client',
                'verbose_name_plural': 'Scores clients',
            },
        ),
        migrations.CreateModel(
            name='InventoryControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('name', models.CharField(default='Inventaire', max_length=100, verbose_name='Nom')),
                ('control_date', models.DateField(verbose_name='Date contrôle')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrôle inventaire',
                'verbose_name_plural': 'Contrôles inventaire',
                'ordering': ['-control_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Date départ')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Arrivée estimée')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='Arrivée réelle')),
                ('status', models.CharField(choices=[('preparing', 'En préparation'), ('shipped', 'Expédié'), ('in_transit', 'En transit'), ('arrived', 'Arrivé'), ('received', 'Réceptionné'), ('cancelled', 'Annulé')], default='preparing', max_length=20, verbose_name='Statut')),
                ('transporter', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('vehicle_info', models.CharField(blank=True, max_length=100, verbose_name='Véhicule/Conteneur')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='N° suivi')),
                ('origin', models.CharField(default='Dakar, Sénégal', max_length=100, verbose_name='Origine')),
                ('destination', models.CharField(default="Abidjan, Côte d'Ivoire", max_length=100, verbose_name='Destination')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('quantity_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité allouée')),
                ('priority', models.IntegerField(default=50, help_text='Plus élevé = plus prioritaire', verbose_name='Priorité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('allocated', 'Alloué'), ('fulfilled', 'Satisfait'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preorders', to='crm.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preorders', to='crm.product')),
                ('target_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorders', to='crm.shipment', verbose_name='Expédition ciblée')),
            ],
            options={
                'verbose_name': 'Pré-commande',
                'verbose_name_plural': 'Pré-commandes',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité reçue')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='crm.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.shipment')),
            ],
            options={
                'verbose_name': 'Ligne expédition',
                'verbose_name_plural': 'Lignes expédition',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour')], max_length=20, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Stock après')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.inventorycontrol')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='crm.product')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='crm.shipment')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité réservée')),
                ('reservation_type', models.CharField(choices=[('order', 'Commande'), ('preorder', 'Pré-commande'), ('hold', 'Blocage'), ('credit', 'Avoir client (stock)')], max_length=20, verbose_name='Type')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='crm.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='crm.order')),
                ('preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='crm.preorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.product')),
            ],
            options={
                'verbose_name': 'Réservation stock',
                'verbose_name_plural': 'Réservations stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité théorique')),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantité physique')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.inventorycontrol')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product')),
            ],
            options={
                'verbose_name': 'Ligne inventaire',
                'verbose_name_plural': 'Lignes inventaire',
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
