# Generated by Django 6.0.2 on 2026-03-02 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_phase4_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro BL')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('delivery_contact', models.CharField(blank=True, max_length=100, verbose_name='Contact livraison')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone livraison')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Date livraison effective')),
                ('transporter', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('vehicle_info', models.CharField(blank=True, max_length=100, verbose_name='Véhicule')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Prêt pour livraison'), ('in_delivery', 'En cours de livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('received_by', models.CharField(blank=True, max_length=100, verbose_name='Réceptionné par')),
                ('signature', models.TextField(blank=True, verbose_name='Signature (base64)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('driver_notes', models.TextField(blank=True, verbose_name='Notes chauffeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='crm.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_delivered', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='crm.order')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité livrée')),
                ('lot_number', models.CharField(blank=True, max_length=50, verbose_name='N° lot')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynote')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product')),
            ],
            options={
                'verbose_name': 'Ligne BL',
                'verbose_name_plural': 'Lignes BL',
            },
        ),
    ]
