# Generated by Django 6.0.2 on 2026-03-02 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_phase5_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('order', 'Commandes'), ('payment', 'Paiements'), ('stock', 'Stock'), ('marketing', 'Marketing'), ('loyalty', 'Fidélité')], max_length=20, verbose_name='Catégorie')),
                ('subject', models.CharField(help_text='Utiliser {{client_name}}, {{amount}}, etc.', max_length=200, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Corps HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte (fallback)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('auto_trigger', models.CharField(blank=True, help_text="Event qui déclenche l'envoi (ex: order_created)", max_length=100, verbose_name='Déclencheur auto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Nom destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Corps HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('related_type', models.CharField(blank=True, max_length=50, verbose_name='Type objet')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name='Message erreur')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='crm.customer')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.emailtemplate')),
            ],
            options={
                'verbose_name': 'Log email',
                'verbose_name_plural': 'Logs email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('trigger_event', models.CharField(choices=[('order_created', 'Nouvelle commande'), ('order_confirmed', 'Commande confirmée'), ('order_delivered', 'Commande livrée'), ('invoice_created', 'Facture créée'), ('payment_received', 'Paiement reçu'), ('payment_due_3d', 'Échéance dans 3 jours'), ('payment_due_7d', 'Retard 7 jours'), ('payment_due_30d', 'Retard 30 jours'), ('stock_arrived', 'Stock arrivé'), ('manual', 'Envoi manuel')], max_length=50, verbose_name='Événement déclencheur')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Ex: {"min_amount": 100000, "customer_type": "B2B"}', verbose_name='Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Dernier déclenchement')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='crm.emailtemplate')),
            ],
            options={
                'verbose_name': 'Règle automatisation',
                'verbose_name_plural': 'Règles automatisation',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
