# Generated by Django 6.0.2 on 2026-03-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_phase6_emailing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Nombre commandes')),
                ('orders_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant commandes')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='Nouveaux clients')),
                ('active_customers', models.PositiveIntegerField(default=0, verbose_name='Clients actifs')),
                ('payments_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Encaissements')),
                ('outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Créances en cours')),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur stock')),
                ('low_stock_products', models.PositiveIntegerField(default=0, verbose_name='Produits stock bas')),
                ('deliveries_count', models.PositiveIntegerField(default=0, verbose_name='Livraisons')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Snapshot KPI',
                'verbose_name_plural': 'Snapshots KPI',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Type')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notes approbation')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande approbation',
                'verbose_name_plural': 'Demandes approbation',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('director', 'Direction'), ('commercial', 'Commercial'), ('cashier', 'Caissier(e)'), ('warehouse', 'Magasinier'), ('accountant', 'Comptable')], default='commercial', max_length=20, verbose_name='Rôle')),
                ('approval_limit', models.DecimalField(decimal_places=2, default=0, help_text="Montant max qu'il peut approuver", max_digits=15, verbose_name='Limite approbation')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nom utilisateur')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('approve', 'Approbation'), ('reject', 'Rejet'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Représentation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log audit',
                'verbose_name_plural': 'Logs audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='crm_auditlo_model_n_9b9867_idx'), models.Index(fields=['user', 'created_at'], name='crm_auditlo_user_id_7bf427_idx')],
            },
        ),
    ]
